# Generated by Django 4.1.5 on 2023-05-12 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_birth", models.DateField()),
                ("location", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=14)),
                ("place_of_work", models.CharField(max_length=60)),
                ("gender", models.CharField(max_length=10)),
                ("marital_status", models.CharField(max_length=10)),
                ("life_connect", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=20)),
                ("specific_life_objective", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
