# Generated by Django 4.1.5 on 2023-05-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Records", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="uuid",
        ),
        migrations.AddField(
            model_name="record",
            name="id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="record",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
