# Generated by Django 4.1.5 on 2023-05-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Records", "0002_remove_record_uuid_record_id_alter_record_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
